export const API_BASE_URL = import.meta.env.VITE_API_URL || '/api';
export const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || window.location.origin;

export const LANGUAGES = {
  ar: 'العربية',
  en: 'English',
} as const;

export const TRANSLATIONS = {
  ar: {
    home: 'الرئيسية',
    reels: 'ريلز',
    friends: 'الأصدقاء',
    messages: 'الرسائل',
    profile: 'الملف الشخصي',
    apiMarket: 'سوق API',
    liveRadar: 'الرادار الحي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    search: 'بحث...',
    likes: 'إعجابات',
    comments: 'تعليقات',
    shares: 'مشاركات',
    follow: 'متابعة',
    unfollow: 'إلغاء المتابعة',
    credits: 'النقاط',
    buyCredits: 'شراء نقاط',
    createPost: 'إنشاء منشور',
    whatThinking: 'ما الذي تفكر فيه؟',
    post: 'نشر',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    viewProfile: 'عرض الملف الشخصي',
    sendMessage: 'إرسال رسالة',
    call: 'اتصال',
    videoCall: 'مكالمة فيديو',
    accept: 'قبول',
    reject: 'رفض',
    endCall: 'إنهاء المكالمة',
    mute: 'كتم الصوت',
    unmute: 'إلغاء الكتم',
    aiTranslate: 'ترجمة بالذكاء الاصطناعي',
    translationEnabled: 'الترجمة مفعلة',
    translationDisabled: 'الترجمة معطلة',
    creditsBalance: 'رصيد النقاط',
    notEnoughCredits: 'رصيد غير كافٍ',
    purchaseSuccess: 'تمت العملية بنجاح',
    purchaseFailed: 'فشلت العملية',
  },
  en: {
    home: 'Home',
    reels: 'Reels',
    friends: 'Friends',
    messages: 'Messages',
    profile: 'Profile',
    apiMarket: 'API Market',
    liveRadar: 'Live Radar',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Sign Up',
    search: 'Search...',
    likes: 'Likes',
    comments: 'Comments',
    shares: 'Shares',
    follow: 'Follow',
    unfollow: 'Unfollow',
    credits: 'Credits',
    buyCredits: 'Buy Credits',
    createPost: 'Create Post',
    whatThinking: "What's on your mind?",
    post: 'Post',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    viewProfile: 'View Profile',
    sendMessage: 'Send Message',
    call: 'Call',
    videoCall: 'Video Call',
    accept: 'Accept',
    reject: 'Reject',
    endCall: 'End Call',
    mute: 'Mute',
    unmute: 'Unmute',
    aiTranslate: 'AI Translate',
    translationEnabled: 'Translation Enabled',
    translationDisabled: 'Translation Disabled',
    creditsBalance: 'Credits Balance',
    notEnoughCredits: 'Insufficient Credits',
    purchaseSuccess: 'Purchase Successful',
    purchaseFailed: 'Purchase Failed',
  }
} as const;

export type Language = keyof typeof LANGUAGES;